export const SUBCATEGORY_LIST_REQUEST = 'SUBCATEGORY_LIST_REQUEST'
export const SUBCATEGORY_LIST_SUCCESS = 'SUBCATEGORY_LIST_SUCCESS'
export const SUBCATEGORY_LIST_FAIL = 'SUBCATEGORY_LIST_FAIL'
export const SUBCATEGORY_LIST_RESET = 'SUBCATEGORY_LIST_RESET'

export const SUBCATEGORY_DETAILS_REQUEST = 'SUBCATEGORY_DETAILS_REQUEST'
export const SUBCATEGORY_DETAILS_SUCCESS = 'SUBCATEGORY_DETAILS_SUCCESS'
export const SUBCATEGORY_DETAILS_FAIL = 'SUBCATEGORY_DETAILS_FAIL'
export const SUBCATEGORY_DETAILS_RESET = 'SUBCATEGORY_DETAILS_RESET'

export const SUBCATEGORY_CREATE_REQUEST = 'SUBCATEGORY_CREATE_REQUEST'
export const SUBCATEGORY_CREATE_SUCCESS = 'SUBCATEGORY_CREATE_SUCCESS'
export const SUBCATEGORY_CREATE_FAIL = 'SUBCATEGORY_CREATE_FAIL'
export const SUBCATEGORY_CREATE_RESET = 'SUBCATEGORY_CREATE_RESET'
